config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :password_resets,     only: [:new, :create, :edit, :update]
  #resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/link', to: 'static_pages#link'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "このサイトについて",   about_path %></li>
      <li><%= link_to "お問い合わせ", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "We Love Tennis", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "ホーム",   root_path %></li>
          <% if logged_in? %>
            <li><%= link_to "ユーザー一覧", users_path %></li>
            <li><%= link_to "おすすめサイト", link_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                アカウント <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "プロフィール", current_user %></li>
                <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "ログアウト", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "ログイン", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
</header>

app/views/layouts/_home_search_form.html.erb
<%= search_form_for @q ,url: root_path do |f| %>
  <%= f.label :content_cont, '投稿検索' %>
  <div class="input-group">
    <%= f.text_field :content_cont, placeholder: "検索したい投稿を入力してください。",
                      class: 'form-control' %>
                      
    <span class="input-group-btn">
        <%= f.submit '検索', class: "btn btn-primary" %>
    </span>

  </div>
<% end %>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
                           'data-turbolinks-track': 'reload' %>
                           
<%= stylesheet_link_tag "https://use.fontawesome.com/releases/v5.0.6/css/all.css" %>

app/views/layouts/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :name_cont, 'ユーザー検索' %>
  <div class="input-group">
    <%= f.text_field :name_cont, placeholder: "検索したい名前を入力してください。",
                      class: 'form-control' %>
                      
    <span class="input-group-btn">
        <%= f.submit '検索', class: "btn btn-primary" %>
    </span>

    
  </div>
<% end %>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>